project:
  type: website
  output-dir: docs

website:
  #title: "SARA"
  favicon: "images/logo.png"
  site-url: "https://sara-edu.github.io/"
  description: "SARA Institute offers free data science education to underrepresented students."
  twitter-card: true
  image: "images/logo.png"
  
  #cookie-consent: true
  
  navbar:
    logo: images/logo.png
    right:
      - text: About  
        menu: 
          - href: overview.qmd
            text: Overview
          - href: events.qmd
            text: Events 
          - href: contact.qmd
            text: Contact us
      - href: courses.qmd
        text: Courses
      - href: support.qmd
        text: Support
      
      
  page-footer:
    background: "#003366"
    left: "SARA Institute &copy; 2023-2024"
    center: "See a bug? [File an issue!](https://github.com/sara-edu/sara-edu.github.io)"
    right: "[Terms & Conditions](t&c.qmd)"
      
format:
  html:
    theme: 
     - cosmo
     - test.scss
    css: styles.css
    toc: false