project:
  type: website
  output-dir: docs

website:
  title: "SARA INSTITUTE"
  favicon: "images/logo_sara.png"
  site-url: "https://sara-edu.github.io/"
  description: "We offer free data science education to underrepresented students."
  twitter-card: true
  image: "images/logo_sara.png"
  
  #cookie-consent: true
  
  navbar:
    #logo: "images/logo_sara.png"
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: courses.qmd
        text: Courses
      # - href: events.qmd
      #   text: Events 
      - href: support.qmd
        text: Support
      - href: contact.qmd
        text: Contact
        
    # tools:
    #   - icon: twitter
    #     href: https://twitter.com
        
  page-footer:
    background: "#000033"
    left: "SARA Institute &copy; 2023-present"
    right: "[Terms & Conditions](t&c.qmd)"
      
format:
  html:
    page-layout: full
    theme: 
     - flatly
     - test.scss
    css: styles.css
    toc: false