project:
  type: website
  output-dir: docs

website:
  #title: "SARA"
  favicon: "images/logo.png"
  twitter-card: true
  image: "images/logo.png"
  site-url: "https://sara-edu.github.io/"
  #cookie-consent: true
  
  navbar:
    logo: images/logo.png
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Us
      - href: course.qmd
        text: Our Courses
      - href: suppot.qmd
        text: Support Us  
      - href: contact.qmd
        text: Contact Us  
      
  page-footer:
    background: "#003366"
    left: "&copy; SARA Institute<br>Sonipat, Haryana 131001, India."
    center: "See a bug?<br>[File an issue!]()"
    right: "[Terms &<br>Conditions](t&c.qmd)"
      
format:
  html:
    theme: 
     - flatly
     - test.scss
    css: styles.css
    toc: false